var igt_a=true,igt_=null;function igt_b(){for(var a=this.q.b,c=0;c<a.length;c++)if(this===a[c])return c;return-1}function igt_c(a){this.q=a;this.i=this.c=this.a=igt_;this.getName=function(){return this.a.innerHTML};this.getNameContainer=function(){return this.a};this.getContentContainer=function(){return this.c};this.getCallback=function(){return this.i};this.getIndex=igt_b}
function igt_d(a){if(arguments.length>0)if(typeof arguments[1]=="object")return this.l(a,arguments[1]);else{var c=arguments[1],b=arguments[2];if(c){if(!this.C.exec(c))throw new Error("addTab(): second argument containing DOM ID contains invalid characters: ["+c+"]");}else c=this.p();return this.l(a,{contentContainer:_gel(c),callback:b})}}
function igt_e(a,c){if(typeof c!="function")throw new Error("addDynamicTab(): second argument must be a function, not ["+typeof c+"]");return this.l(a,{callback:c})}
function igt_f(a,c){var b=typeof c=="object"?c:{},d=-1;if(b.index>=0&&b.index<this.b.length)d=b.index;var e=this.A(a,{contentContainer:b.contentContainer,callback:b.callback,tooltip:b.tooltip}),f=this.g.rows[0];if(this.b.length>0){var g=document.createElement("td");g.className=this.e("tablib_spacerTab");g.appendChild(document.createTextNode(" "));var h=d<0?f.cells[f.cells.length-1]:this.b[d].a;f.insertBefore(g,h);f.insertBefore(e.a,d<0?h:g)}else f.insertBefore(e.a,f.cells[f.cells.length-1]);if(d<
0){d=this.b.length;this.b.push(e)}else{this.b.splice(d,0,e);this.t()}var i=new RegExp(this.o,"i");if(isNaN(parseInt(this.k,10)))if(this.o)a.match(i)&&this.h(e,igt_a);else d==0&&this.h(e,igt_a);else parseInt(this.k,10)==d&&this.h(e,igt_a);this.v++;this.displayTabs(igt_a);this.n(igt_a);return e.c.id}
function igt_g(a){var c=this.b[a];if(!c)throw new Error("removeTab(): first argument is out of range: ["+ +a+"]");if(c==this.d){var b=this.b.length-1;if(b>0)this.h(a<b?this.b[a+1]:this.b[a-1])}var d=this.g.rows[0];if(this.b.length>1)d.removeChild(a==0?c.a.nextSibling:c.a.previousSibling);d.removeChild(c.a);this.f.removeChild(c.c);this.b.splice(a,1);this.n();if(this.b.length==0){this.displayTabs(false);this.k="";this.d=igt_}}
function igt_h(a){this.leftNavContainer.style.display="none";this.rightNavContainer.style.display="none";if(this.g.offsetWidth<=this.tabsContainer.offsetWidth)this.tabsContainer.scrollLeft=0;else{this.leftNavContainer.style.display="";this.rightNavContainer.style.display="";if(this.tabsContainer.scrollLeft+this.tabsContainer.offsetWidth>this.tabsContainer.scrollWidth)this.tabsContainer.scrollLeft=this.tabsContainer.scrollWidth-this.tabsContainer.offsetWidth;else if(this.s&&a)this.tabsContainer.scrollLeft=
this.tabsContainer.scrollWidth}}function igt_i(a,c){var b=10;if(c){a.scrollLeft+=c<0?-b:b;var d=Math.min(b,Math.abs(c)),e=function(){igt_i(a,c<0?c+d:c-d)};setTimeout(e,10)}}function igt_j(a){this.f.style.display=a?"block":"none"}function igt_k(){return this.d}function igt_l(a){if(!this.b[a])throw new Error("setSelectedTab(): first argument is out of range: ["+a+"]");this.h(this.b[a])}
function igt_m(a,c){var b=this.b[a],d=this.b[c];if(!b||!d)throw new Error("moveTab(): arguments are out of range: ["+a+"-"+c+"]");var e=b.a.parentNode,f=b.a.nextSibling;e.insertBefore(b.a,d.a);e.insertBefore(d.a,f);this.b[a]=d;this.b[c]=b}
function igt_n(a,c){if(!(this.d==a)){if(this.d){this.d.a.className=this.e("tablib_unselected");this.d.a.onclick=this.u(this.d);if(this.m)this.d.a.onmouseover=this.d.a.onclick;this.d.c.style.display="none"}a.a.className=this.e("tablib_selected");a.a.onmouseover=a.a.onclick=igt_;a.c.style.display="block";this.d=a;var b=c==igt_a?igt_a:false;b||this.t();typeof a.i=="function"&&a.i(a.c.id)}}function igt_o(){return this.b.concat()}
function igt_p(a,c){if(!a.match(/^(left|center|right)$/))throw new Error("alignTabs(): first argument must be one of: [left, center, right]");var b=this.g.rows[0],d=b.cells[0],e=b.cells[b.cells.length-1],f=isNaN(c)?"3px":c+"px";d.style.width=a=="left"?f:"";e.style.width=a=="right"?f:"";this.g.style.display="none";this.g.style.display=""}
function igt_q(a,c){var b=new igt_c(this);b.c=c.contentContainer?c.contentContainer:igt_;b.i=c.callback?c.callback:igt_;b.a=document.createElement("td");b.a.title=c.tooltip?c.tooltip:"";b.a.innerHTML=a;b.a.className=this.e("tablib_unselected");b.a.onclick=this.u(b);if(this.m)b.a.onmouseover=b.a.onclick;if(b.c)b.c.parentNode!==this.f&&this.f.appendChild(b.c);else{b.c=document.createElement("div");b.c.id=this.p();this.f.appendChild(b.c)}b.c.style.display="none";b.c.className=this.e("tablib_content_container")+
" "+b.c.className;return b}
function igt_r(){var a=document.createElement("table");a.id=this.f.id+"_header";a.className=this.e("tablib_table");a.cellSpacing="0";a.cellPadding="0";var c=document.createElement("tbody"),b=document.createElement("tr");c.appendChild(b);a.appendChild(c);var d=document.createElement("td");d.className=this.e("tablib_emptyTab");d.appendChild(document.createTextNode(" "));b.appendChild(d);b.appendChild(d.cloneNode(igt_a));var e=document.createElement("table");e.id=this.f.id+"_navTable";e.style.width=
"100%";e.cellSpacing="0";e.cellPadding="0";e.style.tableLayout="fixed";var f=document.createElement("tbody"),g=document.createElement("tr");f.appendChild(g);e.appendChild(f);var h=document.createElement("td");h.className=this.e("tablib_emptyTab")+" "+this.e("tablib_navContainer");h.style.textAlign="left";h.style.display="";var i=document.createElement("a");i.href="javascript:void(0)";i.innerHTML="&laquo;";h.appendChild(i);g.appendChild(h);var m=document.createElement("td");g.appendChild(m);var j=
document.createElement("div");j.style.width="100%";j.style.overflow="hidden";j.appendChild(a);m.appendChild(j);var k=document.createElement("td");k.className=this.e("tablib_emptyTab")+" "+this.e("tablib_navContainer");k.style.textAlign="right";k.style.display="";var l=document.createElement("a");l.href="javascript:void(0)";l.innerHTML="&raquo;";k.appendChild(l);g.appendChild(k);i.onclick=function(){igt_i(j,-120)};l.onclick=function(){igt_i(j,120)};if(this.s){var n=i.onclick;i.onclick=l.onclick;l.onclick=
n}if(this.navTable!=igt_)this.f.replaceChild(e,this.navTable);else{this.f.insertBefore(e,this.f.firstChild);var o=this,p=function(){o.n()};_IG_AddDOMEventHandler(window,"resize",p)}this.navTable=e;this.leftNavContainer=h;this.rightNavContainer=k;this.tabsContainer=j;return a}
function igt_s(a){var c="tl_"+this.j,b=a?a:_gel(c);if(!b){b=document.createElement("div");b.id=c;var d=_getGadgetContainer(this.j);if(!d)throw Error("Cannot locate gadget container.  Are you missing a <body> tag?");d.insertBefore(b,d.firstChild)}b.className=this.e("tablib_main_container")+" "+b.className;return b}function igt_t(a){return function(){a.q.h(a)}}function igt_u(){return this.f.id+"_"+this.v}
function igt_v(){try{var a=this.d.getIndex();if(a>=0){this.k=a;this.r.set("selectedTab",a)}}catch(c){}}function igt_w(a){return a+" "+a+this.j}var igt_x=".tablib_table {width: 100%;border-collapse: separate;border-spacing: 0px;empty-cells: show;font-size: 11px;text-align: center;}.tablib_emptyTab {border-bottom: 1px solid #676767;padding: 0px 1px;}.tablib_spacerTab {border-bottom: 1px solid #676767;padding: 0px 1px;width: 1px;}.tablib_selected {padding: 2px;background-color: #ffffff;border: 1px solid #676767;border-bottom-width: 0px;color: #3366cc;font-weight: bold;width: 80px;cursor: default;}.tablib_unselected {padding: 2px;background-color: #dddddd;border: 1px solid #aaaaaa;border-bottom-color: #676767;color: #000000;width: 80px;cursor: pointer;}.tablib_navContainer {width: 10px;vertical-align: middle;}.tablib_navContainer a:link, .tablib_navContainer a:visited, .tablib_navContainer a:hover {color: #3366aa;text-decoration: none;}";
function _IG_Tabs(a,c,b){this.addTab=igt_d;this.addDynamicTab=igt_e;this.setSelectedTab=igt_l;this.getSelectedTab=igt_k;this.moveTab=igt_m;this.removeTab=igt_g;this.getTabs=igt_o;this.alignTabs=igt_p;this.displayTabs=igt_j;this.getHeaderContainer=function(){return this.g};this.setAutoSelect=function(e){this.m=e};this.l=igt_f;this.w=igt_s;this.z=igt_r;this.A=igt_q;this.h=igt_n;this.u=igt_t;this.p=igt_u;this.t=igt_v;this.e=igt_w;this.n=igt_h;this.D=igt_i;if(!a){if(typeof remote_modules!="undefined")throw new Error("Module ID is required for inlined gadgets.");
var d=_args().mid;a=d?d:0}this.j=a;this.B=igt_x;this.C=/^[A-Za-z]([0-9a-zA-Z_:.-]+)?$/;this.r=new _IG_Prefs(this.j);this.k=this.r.getString("selectedTab");this.d=igt_;this.b=[];this.v=0;this.o=c?c:igt_;this.tabsContainer=this.navTable=this.leftNavContainer=this.rightNavContainer=igt_;this.s=document.body.dir=="rtl";this.m=false;this.f=this.w(b);this.g=this.z();this.displayTabs(false);_IG_LoadCss(this.B)}
_exportClass("google.gadgets","Tabs",_IG_Tabs,["addTab",igt_d,"addDynamicTab",igt_e,"getSelectedTab",igt_k,"setSelectedTab",igt_l,"swapTabs",igt_m,"removeTab",igt_g,"getTabs",igt_o,"alignTabs",igt_p,"displayTabs",igt_j,"getHeaderContainer",function(){return this.g}]);
function _IG_GetFlashMajorVersion(){var e=0;if(navigator.plugins&&navigator.mimeTypes&&navigator.mimeTypes.length){var b=navigator.plugins["Shockwave Flash"];if(b&&b.description)e=parseInt(b.description.match(/[0-9]+/)[0],10)}else for(b=10;b>0;b--)try{new ActiveXObject("ShockwaveFlash.ShockwaveFlash."+b);return b}catch(a){}return e}
function _IG_EmbedCachedFlash(e,b,a){var g=arguments;if(typeof g[0]=="string"){var h=a||{},f=[];_et&&f.push("et",_esc(_et));!isNaN(h.refreshInterval)&&h.refreshInterval>=0&&f.push("max_age",h.refreshInterval);g[0]="http://www.gmodules.com/ig/proxy/"+f.join(",")+"/"+g[0]}_IG_EmbedFlash.apply(this,g)}
function _IG_EmbedFlash(e,b,a){if(typeof e!="string")throw new Error("The first argument to _IG_EmbedFlash must be a string.");switch(typeof b){case "string":b=_gel(b);case "object":if(b&&typeof b.innerHTML=="string")break;default:throw new Error("The second argument to _IG_EmbedFlash must be an existing HTML element.");}switch(typeof a){case "undefined":a={};case "object":break;default:throw new Error("The third argument to _IG_EmbedFlash must be either an object or undefined.");}var g=_IG_GetFlashMajorVersion();
if(g){var h=parseInt(a.swf_version,10);if(isNaN(h))h=0;if(g>=h){for(var f in a){var k=f.toLowerCase();if(f!=k){a[k]=a[f];delete a[f]}}if(!a.allowscriptaccess)a.allowscriptaccess="always";if(!a.width)a.width="100%";if(!a.height)a.height="100%";if(typeof a.base!="string")a.base=e.match(/^[^?#]+\//)[0];if(typeof a.wmode!="string")a.wmode="opaque";if(typeof _IG_Prefs=="function"){var j=(new _IG_Prefs(a.swf_module_id)).getPreloadedString();if(j)a.flashvars=a.flashvars?a.flashvars+"&"+j:j}var l=Math.floor(Math.random()*
10000000);if(!window.name)window.name="gga_iframe"+l;if(!a.id)a.id="swfContainer"+l;a.flashvars=(a.flashvars?a.flashvars+"&":"")+"_IG_GadgetContainer="+_esc(window.name)+"&_ADS_GadgetContainer="+_esc(window.name);var d;if(navigator.plugins&&navigator.mimeTypes&&navigator.mimeTypes.length){a.type="application/x-shockwave-flash";a.src=e;d="<embed";for(var c in a)/^swf_/.test(c)||(d+=" "+c+"='"+a[c]+"'");d+=" /></embed>"}else{a.movie=e;var i={width:a.width,height:a.height,classid:"clsid:D27CDB6E-AE6D-11CF-96B8-444553540000"};
if(a.id)i.id=a.id;d="<object";for(c in i)d+=" "+c+"='"+i[c]+"'";d+=">";for(c in a)if(!/^swf_/.test(c)&&!i[c])d+="<param name='"+c+"' value='"+a[c]+"' />";d+="</object>"}b.innerHTML=d;return true}}return false}_exportSymbols("google.gadgets.Flash",["getMajorVersion",_IG_GetFlashMajorVersion,"embedCachedFlash",_IG_EmbedCachedFlash,"embedFlash",_IG_EmbedFlash]);
